public enum BWMenuTextEnum
{
	DeleteWorldConfirmation,
	DeleteUntitledWorldConfirmation,
	DeleteModelConfirmation,
	DeleteUntitledModelConfirmation,
	RemoveFromBookmarkedWorldsConfirmation,
	ReportWorldConfirmation,
	WorldPublishOnCooldownMessage,
	WorldReportSuccessMessage,
	WorldPublishMissingDataMessage,
	ResetToDefaultSettings,
	MissingWorldTitleNotification,
	MissingWorldDescriptionNotification,
	MissingWorldCategoryNotification,
	PublishFailedProfanityCheckMessage,
	PublishWorldConfirmation,
	ReportModelConfirmation,
	ModelReportSucessMessage
}
