public enum DialogTypeEnum
{
	GenericOneButton,
	GenericTwoButton,
	GenericTwoButtonWithTiles,
	ModelPurchaseConfirmation,
	SaveModel,
	SetPurchasePrompt,
	StringParameterInput,
	CustomSignalName,
	GenericMultiButton,
	TwoButtonWithTilesAndExtraText,
	MaximumModels,
	GoToStoreConfirmationPrompt,
	WorldIdEntry,
	CurrentUserWorldList,
	GenericMultiButtonWithTiles,
	ProfilePictureConfirmation,
	EscapeMenu
}
