public enum WorldPublicationStatus
{
	MODERATION_PENDING = 0,
	MODERATION_APPROVED = 1,
	MODERATION_REJECTED = 2,
	DELETED_BY_AUTHOR = 4,
	NOT_PUBLISHED = 5,
	REPORT_REJECTED = 9,
	COMMUNITY_MODERATION_PENDING = 10,
	COMMUNITY_MODERATION_APPROVED = 11,
	COMMUNITY_MODERATION_REJECTED = 12
}
